// The machine code generated by your program should go here
// add 
@SP
AM=M-1
D=M
@SP
AM=M-1
M=D+M
@SP
M=M+1

// add
@SP
AM=M-1
D=M
@SP
AM=M-1
M=D+M
@SP
M=M+1

(END)
@END
0;JMP