// The machine code generated by your program should go here
// eq 0
@SP
AM=M-1
D=M
@SP
A=M-1
D=M-D
M=-1
@eqTrue0
D;JEQ
@SP
A=M-1
M=0
(eqTrue0)

// eq 1
@SP
AM=M-1
D=M
@SP
A=M-1
D=M-D
M=-1
@eqTrue1
D;JEQ
@SP
A=M-1
M=0
(eqTrue1)

(END)
@END
0;JMP