// The machine code generated by your program should go here
// gt 0
@SP
AM=M-1
D=M
@SP
A=M-1
D=M-D
M=-1
@gtTrue0
D;JGT
@SP
A=M-1
M=0
(gtTrue0)

// gt 1
@SP
AM=M-1
D=M
@SP
A=M-1
D=M-D
M=-1
@gtTrue1
D;JGT
@SP
A=M-1
M=0
(gtTrue1)

(END)
@END
0;JMP