// The machine code generated by your program should go here
// lt 0
@SP
AM=M-1
D=M
@SP
A=M-1
D=M-D
M=-1
@ltTrue0
D;JLT
@SP
A=M-1
M=0
(ltTrue0)

// lt 1
@SP
AM=M-1
D=M
@SP
A=M-1
D=M-D
M=-1
@ltTrue1
D;JLT
@SP
A=M-1
M=0
(ltTrue1)

(END)
@END
0;JMP