// The machine code generated by your program should go here
// pop static10
@SP
AM=M-1
D=M
@26
M=D

// pop temp7
@7
D=A
@5
D=A+D
@R13
M=D
@SP
AM=M-1
D=M
@R13
A=M
M=D

(END)
@END
0;JMP