// The machine code generated by your program should go here
// push constant0
@0
D=A
@SP
A=M
M=D
@SP
M=M+1

// push constant32767
@32767
D=A
@SP
A=M
M=D
@SP
M=M+1

(END)
@END
0;JMP
