// The machine code generated by your program should go here
// sub 
@SP
AM=M-1
D=M
@SP
AM=M-1
M=M-D
@SP
M=M+1

// sub
@SP
AM=M-1
D=M
@SP
AM=M-1
M=M-D
@SP
M=M+1

(END)
@END
0;JMP